# Generated by Django 4.2.2 on 2023-07-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparing',
            field=models.TextField(null=True),
        ),
    ]
